name: dell-csi-drivers
version: 1.0.0
appVersion: 1.0.0
description: |
  Dell EMC CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a Unity StorageClass for Unity and Isilon.
keywords:
- csi
- storage
sources:
- https://github.com/dell/csi-unity
maintainers:
- name: DellEMC
engine: gotpl
