## Common parametes
storageType: unity
certSecretCount: 1
volumeNamePrefix: csivol
snapNamePrefix: csi-snap
imagePullPolicy: IfNotPresent
controllerCount: 2

controller:
  nodeSelector:
  tolerations:
  
node:
  nodeSelector:
  tolerations:
  dnsPolicy: "ClusterFirstWithHostNet"
  
podmon:
  enabled: false
  image:


##Unity

maxUnityVolumesPerNode: 0
syncNodeInfoInterval: 15
allowRWOMultiPodAccess: "false"


##Isilon
allowedNetworks: []
isiPort: "8080"
isiInsecure: "true"
isiAccessZone: "System"
enableDebug: "true"
verbose: 1
enableQuota: "true"
noProbeOnStart: "false"
isiPath: "/ifs/data/csi"
autoProbe: "true"
nfsV3: "false"
enableCustomTopology: "false"
maxIsilonVolumesPerNode: 0


## All images
images:
  attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0
  provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
  snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
  registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
  resizer:  quay.io/k8scsi/csi-resizer:v1.1.0
  
  driver: 
    unity: dellemc/csi-unity:v1.5.0
    isilon: dellemc/csi-isilon:v1.5.0
