{{- if or (eq .Capabilities.KubeVersion.Minor "17") (eq .Capabilities.KubeVersion.Minor "17+")}}
apiVersion: storage.k8s.io/v1beta1
{{- else }}
apiVersion: storage.k8s.io/v1
{{- end }}
kind: CSIDriver
{{ if eq .Values.storageType "unity" }}
metadata:
    name: csi-unity.dellemc.com
{{ else if eq .Values.storageType "powerscale" }}
metadata:
    name: csi-isilon.dellemc.com
{{ end }}
spec:
    attachRequired: true
    podInfoOnMount: true
    volumeLifecycleModes:
    - Persistent
    - Ephemeral
